<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-MNL8F5BN" name="com.mmt.practise.classretryanalyzer" tests="5" failures="0" timestamp="2021-10-22T20:48:45 IST" time="0.009" errors="1">
  <testcase name="sampleTest" time="0.001" classname="com.mmt.practise.classretryanalyzer">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <system-out/>
  <testcase name="sampleTest" time="0.001" classname="com.mmt.practise.classretryanalyzer">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <system-out/>
  <testcase name="sampleTest" time="0.001" classname="com.mmt.practise.classretryanalyzer">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.mmt.practise.classretryanalyzer.sampleTest(classretryanalyzer.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sampleTest -->
  <system-out/>
  <testcase name="sampleTest" time="0.001" classname="com.mmt.practise.classretryanalyzer">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <system-out/>
  <testcase name="sampleTest" time="0.005" classname="com.mmt.practise.classretryanalyzer">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <system-out/>
</testsuite> <!-- com.mmt.practise.classretryanalyzer -->
